class_name SaveConstants
extends RefCounted
## 存档数据键名常量（SAV-1 提取自 save_manager.gd）

## ─── 存档数据键名常量 ───
const SK_SCHEMA_VERSION: String = "__schema_version"
const SK_BLUEPRINT: String = "blueprint"
const SK_BASIC_RESOURCES: String = "basic_resources"
const SK_PHASE_LAW: String = "phase_law"
const SK_QUEST: String = "quest"
const SK_FACTION_SYSTEM: String = "faction_system"
const SK_AFFIX_DATA: String = "affix_data"
const SK_LEVEL_PROGRESS: String = "level_progress"
const SK_DROP_MANAGER: String = "drop_manager"
const SK_GAME: String = "game"
const SK_CURRENT_LEVEL: String = "current_level"
const SK_PHASE_SLOTS: String = "phase_slots"
const SK_PHASE_SLOTS_ORDER: String = "phase_slots_order"
const SK_PHASE_INSTRUMENT: String = "phase_instrument"
const SK_BACKPACK_EXTRA_IDS: String = "backpack_extra_ids"
const SK_LORE: String = "lore"
const SK_STAT_BOOST: String = "stat_boost"
const SK_ACHIEVEMENT: String = "achievement"
const SK_DAILY_TASK: String = "daily_task"
const SK_STATISTICS: String = "statistics"
const SK_CARD_ENHANCEMENT: String = "card_enhancement"
const SK_LAW_SHARDS: String = "law_shards"
const SK_TUTORIAL_PROGRESS: String = "tutorial_progress"
const SK_STORY_PROGRESS: String = "story_progress"
const SK_CHARACTERS: String = "characters"
const SK_CHALLENGE_RECORDS: String = "challenge_records"
const SK_CARD_COLLECTION: String = "card_collection"
const SK_LEADERBOARD: String = "leaderboard"
const SK_LEGACY_COMPANY_REP: String = "_legacy_company_rep"
